// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: m0/peer/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetPeerIDRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetPeerIDRequest) Reset()         { *m = QueryGetPeerIDRequest{} }
func (m *QueryGetPeerIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPeerIDRequest) ProtoMessage()    {}
func (*QueryGetPeerIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2c53687ad9db3d0, []int{0}
}
func (m *QueryGetPeerIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPeerIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPeerIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPeerIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPeerIDRequest.Merge(m, src)
}
func (m *QueryGetPeerIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPeerIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPeerIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPeerIDRequest proto.InternalMessageInfo

func (m *QueryGetPeerIDRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetPeerIDResponse struct {
	PeerID *PeerID `protobuf:"bytes,1,opt,name=PeerID,proto3" json:"PeerID,omitempty"`
}

func (m *QueryGetPeerIDResponse) Reset()         { *m = QueryGetPeerIDResponse{} }
func (m *QueryGetPeerIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPeerIDResponse) ProtoMessage()    {}
func (*QueryGetPeerIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2c53687ad9db3d0, []int{1}
}
func (m *QueryGetPeerIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPeerIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPeerIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPeerIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPeerIDResponse.Merge(m, src)
}
func (m *QueryGetPeerIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPeerIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPeerIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPeerIDResponse proto.InternalMessageInfo

func (m *QueryGetPeerIDResponse) GetPeerID() *PeerID {
	if m != nil {
		return m.PeerID
	}
	return nil
}

type QueryAllPeerIDRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPeerIDRequest) Reset()         { *m = QueryAllPeerIDRequest{} }
func (m *QueryAllPeerIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPeerIDRequest) ProtoMessage()    {}
func (*QueryAllPeerIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2c53687ad9db3d0, []int{2}
}
func (m *QueryAllPeerIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPeerIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPeerIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPeerIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPeerIDRequest.Merge(m, src)
}
func (m *QueryAllPeerIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPeerIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPeerIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPeerIDRequest proto.InternalMessageInfo

func (m *QueryAllPeerIDRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPeerIDResponse struct {
	PeerID     []*PeerID           `protobuf:"bytes,1,rep,name=PeerID,proto3" json:"PeerID,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPeerIDResponse) Reset()         { *m = QueryAllPeerIDResponse{} }
func (m *QueryAllPeerIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPeerIDResponse) ProtoMessage()    {}
func (*QueryAllPeerIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2c53687ad9db3d0, []int{3}
}
func (m *QueryAllPeerIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPeerIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPeerIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPeerIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPeerIDResponse.Merge(m, src)
}
func (m *QueryAllPeerIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPeerIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPeerIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPeerIDResponse proto.InternalMessageInfo

func (m *QueryAllPeerIDResponse) GetPeerID() []*PeerID {
	if m != nil {
		return m.PeerID
	}
	return nil
}

func (m *QueryAllPeerIDResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetPeerIDRequest)(nil), "liubaninc.m0.peer.QueryGetPeerIDRequest")
	proto.RegisterType((*QueryGetPeerIDResponse)(nil), "liubaninc.m0.peer.QueryGetPeerIDResponse")
	proto.RegisterType((*QueryAllPeerIDRequest)(nil), "liubaninc.m0.peer.QueryAllPeerIDRequest")
	proto.RegisterType((*QueryAllPeerIDResponse)(nil), "liubaninc.m0.peer.QueryAllPeerIDResponse")
}

func init() { proto.RegisterFile("m0/peer/query.proto", fileDescriptor_e2c53687ad9db3d0) }

var fileDescriptor_e2c53687ad9db3d0 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0xaf, 0x12, 0x31,
	0x14, 0xc5, 0x29, 0x06, 0x12, 0xea, 0xca, 0x2a, 0x46, 0xd0, 0x4c, 0x64, 0x34, 0x0a, 0x26, 0xb6,
	0x80, 0x7b, 0x13, 0x0c, 0x91, 0x10, 0x37, 0xc8, 0xd2, 0x0d, 0xe9, 0x40, 0x33, 0x36, 0x99, 0x69,
	0x87, 0x69, 0xc7, 0x40, 0x8c, 0x1b, 0xdd, 0xb8, 0x34, 0xd1, 0x85, 0x1f, 0xc9, 0x25, 0x89, 0x1b,
	0x97, 0x06, 0xde, 0x07, 0x79, 0x99, 0x69, 0x79, 0x6f, 0xf8, 0x97, 0xc7, 0x66, 0x92, 0x69, 0xcf,
	0xb9, 0xe7, 0x77, 0x7b, 0x2f, 0xbc, 0x1b, 0xb6, 0x49, 0xc4, 0x58, 0x4c, 0xe6, 0x09, 0x8b, 0x97,
	0x38, 0x8a, 0xa5, 0x96, 0xe8, 0x4e, 0xc0, 0x13, 0x8f, 0x0a, 0x2e, 0xa6, 0x38, 0x6c, 0xe3, 0xf4,
	0xba, 0xfe, 0xc8, 0x97, 0xd2, 0x0f, 0x18, 0xa1, 0x11, 0x27, 0x54, 0x08, 0xa9, 0xa9, 0xe6, 0x52,
	0x28, 0x63, 0xa8, 0xbf, 0x98, 0x4a, 0x15, 0x4a, 0x45, 0x3c, 0xaa, 0x98, 0xa9, 0x44, 0x3e, 0x75,
	0x3c, 0xa6, 0x69, 0x87, 0x44, 0xd4, 0xe7, 0x22, 0x13, 0x5b, 0x6d, 0x75, 0x9b, 0x98, 0x7e, 0x26,
	0x7c, 0x66, 0x8e, 0xdd, 0x97, 0xb0, 0xfa, 0x3e, 0x35, 0x0e, 0x98, 0x1e, 0x31, 0x16, 0x0f, 0xfb,
	0x63, 0x36, 0x4f, 0x98, 0xd2, 0xe8, 0x1e, 0x2c, 0x71, 0x31, 0x63, 0x8b, 0x07, 0xe0, 0x31, 0x68,
	0x56, 0xc6, 0xe6, 0xc7, 0x7d, 0x07, 0xef, 0xef, 0xcb, 0x55, 0x24, 0x85, 0x62, 0xa8, 0x03, 0xcb,
	0xe6, 0x24, 0x33, 0xdc, 0xee, 0xd6, 0xf0, 0x41, 0x37, 0xd8, 0x5a, 0xac, 0xd0, 0x9d, 0xd8, 0xec,
	0x5e, 0x10, 0xec, 0x66, 0xbf, 0x85, 0xf0, 0x9a, 0xdf, 0xd6, 0x7b, 0x86, 0x4d, 0xb3, 0x38, 0x6d,
	0x16, 0x9b, 0x67, 0xb3, 0xcd, 0xe2, 0x11, 0xf5, 0x99, 0xf5, 0x8e, 0x73, 0x4e, 0xf7, 0x17, 0xb0,
	0xb8, 0xb9, 0x84, 0x23, 0xb8, 0xb7, 0xce, 0xc2, 0x45, 0x83, 0x1d, 0xaa, 0x62, 0x46, 0xf5, 0xfc,
	0x46, 0x2a, 0x93, 0x97, 0xc7, 0xea, 0xfe, 0x2e, 0xc2, 0x52, 0x86, 0x85, 0xbe, 0x83, 0x2d, 0x06,
	0x6a, 0x1e, 0x01, 0x38, 0x3a, 0x99, 0x7a, 0xeb, 0x0c, 0xa5, 0x49, 0x75, 0x5b, 0x5f, 0xff, 0x5e,
	0xfc, 0x2c, 0x3e, 0x41, 0x0d, 0x72, 0x65, 0x21, 0xf9, 0x3d, 0x18, 0xf6, 0xc9, 0xe7, 0x6c, 0xb0,
	0x5f, 0xd0, 0x37, 0x00, 0x2b, 0xc6, 0xdd, 0x0b, 0x82, 0xd3, 0x34, 0xfb, 0xb3, 0x3a, 0x4d, 0x73,
	0xf0, 0xe6, 0x6e, 0x23, 0xa3, 0x79, 0x88, 0x6a, 0x27, 0x69, 0xde, 0xbc, 0xfe, 0xb3, 0x76, 0xc0,
	0x6a, 0xed, 0x80, 0xff, 0x6b, 0x07, 0xfc, 0xd8, 0x38, 0x85, 0xd5, 0xc6, 0x29, 0xfc, 0xdb, 0x38,
	0x85, 0x0f, 0x4f, 0x7d, 0xae, 0x3f, 0x26, 0x1e, 0x9e, 0xca, 0x70, 0xd7, 0xbe, 0x30, 0x05, 0xf4,
	0x32, 0x62, 0xca, 0x2b, 0x67, 0x5b, 0xfd, 0xea, 0x32, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xe5, 0x36,
	0x7b, 0x60, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a peerID by index.
	PeerID(ctx context.Context, in *QueryGetPeerIDRequest, opts ...grpc.CallOption) (*QueryGetPeerIDResponse, error)
	// Queries a list of peerID items.
	PeerIDAll(ctx context.Context, in *QueryAllPeerIDRequest, opts ...grpc.CallOption) (*QueryAllPeerIDResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) PeerID(ctx context.Context, in *QueryGetPeerIDRequest, opts ...grpc.CallOption) (*QueryGetPeerIDResponse, error) {
	out := new(QueryGetPeerIDResponse)
	err := c.cc.Invoke(ctx, "/liubaninc.m0.peer.Query/PeerID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PeerIDAll(ctx context.Context, in *QueryAllPeerIDRequest, opts ...grpc.CallOption) (*QueryAllPeerIDResponse, error) {
	out := new(QueryAllPeerIDResponse)
	err := c.cc.Invoke(ctx, "/liubaninc.m0.peer.Query/PeerIDAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a peerID by index.
	PeerID(context.Context, *QueryGetPeerIDRequest) (*QueryGetPeerIDResponse, error)
	// Queries a list of peerID items.
	PeerIDAll(context.Context, *QueryAllPeerIDRequest) (*QueryAllPeerIDResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) PeerID(ctx context.Context, req *QueryGetPeerIDRequest) (*QueryGetPeerIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PeerID not implemented")
}
func (*UnimplementedQueryServer) PeerIDAll(ctx context.Context, req *QueryAllPeerIDRequest) (*QueryAllPeerIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PeerIDAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_PeerID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPeerIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PeerID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liubaninc.m0.peer.Query/PeerID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PeerID(ctx, req.(*QueryGetPeerIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PeerIDAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPeerIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PeerIDAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liubaninc.m0.peer.Query/PeerIDAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PeerIDAll(ctx, req.(*QueryAllPeerIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "liubaninc.m0.peer.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PeerID",
			Handler:    _Query_PeerID_Handler,
		},
		{
			MethodName: "PeerIDAll",
			Handler:    _Query_PeerIDAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "m0/peer/query.proto",
}

func (m *QueryGetPeerIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPeerIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPeerIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPeerIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPeerIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPeerIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PeerID != nil {
		{
			size, err := m.PeerID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPeerIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPeerIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPeerIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPeerIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPeerIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPeerIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.PeerID) > 0 {
		for iNdEx := len(m.PeerID) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PeerID[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetPeerIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPeerIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PeerID != nil {
		l = m.PeerID.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPeerIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPeerIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PeerID) > 0 {
		for _, e := range m.PeerID {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetPeerIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPeerIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPeerIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPeerIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPeerIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPeerIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PeerID == nil {
				m.PeerID = &PeerID{}
			}
			if err := m.PeerID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPeerIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPeerIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPeerIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPeerIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPeerIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPeerIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PeerID = append(m.PeerID, &PeerID{})
			if err := m.PeerID[len(m.PeerID)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
