// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: m0/wasm/genesis.proto

package liubaninc.m0.wasm;

public final class Genesis {
  private Genesis() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GenesisStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:liubaninc.m0.wasm.GenesisState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * params defines all the paramaters of the module.
     * </pre>
     *
     * <code>.liubaninc.m0.wasm.Params params = 3 [(.gogoproto.nullable) = false];</code>
     */
    boolean hasParams();
    /**
     * <pre>
     * params defines all the paramaters of the module.
     * </pre>
     *
     * <code>.liubaninc.m0.wasm.Params params = 3 [(.gogoproto.nullable) = false];</code>
     */
    liubaninc.m0.wasm.Genesis.Params getParams();
    /**
     * <pre>
     * params defines all the paramaters of the module.
     * </pre>
     *
     * <code>.liubaninc.m0.wasm.Params params = 3 [(.gogoproto.nullable) = false];</code>
     */
    liubaninc.m0.wasm.Genesis.ParamsOrBuilder getParamsOrBuilder();

    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/state
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
     */
    java.util.List<liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy> 
        getApproveDeployListList();
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/state
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
     */
    liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy getApproveDeployList(int index);
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/state
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
     */
    int getApproveDeployListCount();
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/state
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
     */
    java.util.List<? extends liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeployOrBuilder> 
        getApproveDeployListOrBuilderList();
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/state
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
     */
    liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeployOrBuilder getApproveDeployListOrBuilder(
        int index);

    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/stateField
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
     */
    java.util.List<liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy> 
        getProposeDeployListList();
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/stateField
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
     */
    liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy getProposeDeployList(int index);
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/stateField
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
     */
    int getProposeDeployListCount();
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/stateField
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
     */
    java.util.List<? extends liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeployOrBuilder> 
        getProposeDeployListOrBuilderList();
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/stateField
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
     */
    liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeployOrBuilder getProposeDeployListOrBuilder(
        int index);
  }
  /**
   * <pre>
   * GenesisState defines the wasm module's genesis state.
   * </pre>
   *
   * Protobuf type {@code liubaninc.m0.wasm.GenesisState}
   */
  public  static final class GenesisState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:liubaninc.m0.wasm.GenesisState)
      GenesisStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GenesisState.newBuilder() to construct.
    private GenesisState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenesisState() {
      approveDeployList_ = java.util.Collections.emptyList();
      proposeDeployList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GenesisState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                proposeDeployList_ = new java.util.ArrayList<liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy>();
                mutable_bitField0_ |= 0x00000004;
              }
              proposeDeployList_.add(
                  input.readMessage(liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                approveDeployList_ = new java.util.ArrayList<liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy>();
                mutable_bitField0_ |= 0x00000002;
              }
              approveDeployList_.add(
                  input.readMessage(liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy.parser(), extensionRegistry));
              break;
            }
            case 26: {
              liubaninc.m0.wasm.Genesis.Params.Builder subBuilder = null;
              if (params_ != null) {
                subBuilder = params_.toBuilder();
              }
              params_ = input.readMessage(liubaninc.m0.wasm.Genesis.Params.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(params_);
                params_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          proposeDeployList_ = java.util.Collections.unmodifiableList(proposeDeployList_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          approveDeployList_ = java.util.Collections.unmodifiableList(approveDeployList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return liubaninc.m0.wasm.Genesis.internal_static_liubaninc_m0_wasm_GenesisState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return liubaninc.m0.wasm.Genesis.internal_static_liubaninc_m0_wasm_GenesisState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              liubaninc.m0.wasm.Genesis.GenesisState.class, liubaninc.m0.wasm.Genesis.GenesisState.Builder.class);
    }

    private int bitField0_;
    public static final int PARAMS_FIELD_NUMBER = 3;
    private liubaninc.m0.wasm.Genesis.Params params_;
    /**
     * <pre>
     * params defines all the paramaters of the module.
     * </pre>
     *
     * <code>.liubaninc.m0.wasm.Params params = 3 [(.gogoproto.nullable) = false];</code>
     */
    public boolean hasParams() {
      return params_ != null;
    }
    /**
     * <pre>
     * params defines all the paramaters of the module.
     * </pre>
     *
     * <code>.liubaninc.m0.wasm.Params params = 3 [(.gogoproto.nullable) = false];</code>
     */
    public liubaninc.m0.wasm.Genesis.Params getParams() {
      return params_ == null ? liubaninc.m0.wasm.Genesis.Params.getDefaultInstance() : params_;
    }
    /**
     * <pre>
     * params defines all the paramaters of the module.
     * </pre>
     *
     * <code>.liubaninc.m0.wasm.Params params = 3 [(.gogoproto.nullable) = false];</code>
     */
    public liubaninc.m0.wasm.Genesis.ParamsOrBuilder getParamsOrBuilder() {
      return getParams();
    }

    public static final int APPROVEDEPLOYLIST_FIELD_NUMBER = 2;
    private java.util.List<liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy> approveDeployList_;
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/state
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
     */
    public java.util.List<liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy> getApproveDeployListList() {
      return approveDeployList_;
    }
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/state
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
     */
    public java.util.List<? extends liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeployOrBuilder> 
        getApproveDeployListOrBuilderList() {
      return approveDeployList_;
    }
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/state
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
     */
    public int getApproveDeployListCount() {
      return approveDeployList_.size();
    }
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/state
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
     */
    public liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy getApproveDeployList(int index) {
      return approveDeployList_.get(index);
    }
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/state
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
     */
    public liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeployOrBuilder getApproveDeployListOrBuilder(
        int index) {
      return approveDeployList_.get(index);
    }

    public static final int PROPOSEDEPLOYLIST_FIELD_NUMBER = 1;
    private java.util.List<liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy> proposeDeployList_;
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/stateField
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
     */
    public java.util.List<liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy> getProposeDeployListList() {
      return proposeDeployList_;
    }
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/stateField
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
     */
    public java.util.List<? extends liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeployOrBuilder> 
        getProposeDeployListOrBuilderList() {
      return proposeDeployList_;
    }
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/stateField
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
     */
    public int getProposeDeployListCount() {
      return proposeDeployList_.size();
    }
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/stateField
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
     */
    public liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy getProposeDeployList(int index) {
      return proposeDeployList_.get(index);
    }
    /**
     * <pre>
     * this line is used by starport scaffolding # genesis/proto/stateField
     * </pre>
     *
     * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
     */
    public liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeployOrBuilder getProposeDeployListOrBuilder(
        int index) {
      return proposeDeployList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < proposeDeployList_.size(); i++) {
        output.writeMessage(1, proposeDeployList_.get(i));
      }
      for (int i = 0; i < approveDeployList_.size(); i++) {
        output.writeMessage(2, approveDeployList_.get(i));
      }
      if (params_ != null) {
        output.writeMessage(3, getParams());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < proposeDeployList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, proposeDeployList_.get(i));
      }
      for (int i = 0; i < approveDeployList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, approveDeployList_.get(i));
      }
      if (params_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getParams());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof liubaninc.m0.wasm.Genesis.GenesisState)) {
        return super.equals(obj);
      }
      liubaninc.m0.wasm.Genesis.GenesisState other = (liubaninc.m0.wasm.Genesis.GenesisState) obj;

      if (hasParams() != other.hasParams()) return false;
      if (hasParams()) {
        if (!getParams()
            .equals(other.getParams())) return false;
      }
      if (!getApproveDeployListList()
          .equals(other.getApproveDeployListList())) return false;
      if (!getProposeDeployListList()
          .equals(other.getProposeDeployListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasParams()) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParams().hashCode();
      }
      if (getApproveDeployListCount() > 0) {
        hash = (37 * hash) + APPROVEDEPLOYLIST_FIELD_NUMBER;
        hash = (53 * hash) + getApproveDeployListList().hashCode();
      }
      if (getProposeDeployListCount() > 0) {
        hash = (37 * hash) + PROPOSEDEPLOYLIST_FIELD_NUMBER;
        hash = (53 * hash) + getProposeDeployListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static liubaninc.m0.wasm.Genesis.GenesisState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static liubaninc.m0.wasm.Genesis.GenesisState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static liubaninc.m0.wasm.Genesis.GenesisState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static liubaninc.m0.wasm.Genesis.GenesisState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static liubaninc.m0.wasm.Genesis.GenesisState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static liubaninc.m0.wasm.Genesis.GenesisState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static liubaninc.m0.wasm.Genesis.GenesisState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static liubaninc.m0.wasm.Genesis.GenesisState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static liubaninc.m0.wasm.Genesis.GenesisState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static liubaninc.m0.wasm.Genesis.GenesisState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static liubaninc.m0.wasm.Genesis.GenesisState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static liubaninc.m0.wasm.Genesis.GenesisState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(liubaninc.m0.wasm.Genesis.GenesisState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * GenesisState defines the wasm module's genesis state.
     * </pre>
     *
     * Protobuf type {@code liubaninc.m0.wasm.GenesisState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:liubaninc.m0.wasm.GenesisState)
        liubaninc.m0.wasm.Genesis.GenesisStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return liubaninc.m0.wasm.Genesis.internal_static_liubaninc_m0_wasm_GenesisState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return liubaninc.m0.wasm.Genesis.internal_static_liubaninc_m0_wasm_GenesisState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                liubaninc.m0.wasm.Genesis.GenesisState.class, liubaninc.m0.wasm.Genesis.GenesisState.Builder.class);
      }

      // Construct using liubaninc.m0.wasm.Genesis.GenesisState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getApproveDeployListFieldBuilder();
          getProposeDeployListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (paramsBuilder_ == null) {
          params_ = null;
        } else {
          params_ = null;
          paramsBuilder_ = null;
        }
        if (approveDeployListBuilder_ == null) {
          approveDeployList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          approveDeployListBuilder_.clear();
        }
        if (proposeDeployListBuilder_ == null) {
          proposeDeployList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          proposeDeployListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return liubaninc.m0.wasm.Genesis.internal_static_liubaninc_m0_wasm_GenesisState_descriptor;
      }

      @java.lang.Override
      public liubaninc.m0.wasm.Genesis.GenesisState getDefaultInstanceForType() {
        return liubaninc.m0.wasm.Genesis.GenesisState.getDefaultInstance();
      }

      @java.lang.Override
      public liubaninc.m0.wasm.Genesis.GenesisState build() {
        liubaninc.m0.wasm.Genesis.GenesisState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public liubaninc.m0.wasm.Genesis.GenesisState buildPartial() {
        liubaninc.m0.wasm.Genesis.GenesisState result = new liubaninc.m0.wasm.Genesis.GenesisState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (paramsBuilder_ == null) {
          result.params_ = params_;
        } else {
          result.params_ = paramsBuilder_.build();
        }
        if (approveDeployListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            approveDeployList_ = java.util.Collections.unmodifiableList(approveDeployList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.approveDeployList_ = approveDeployList_;
        } else {
          result.approveDeployList_ = approveDeployListBuilder_.build();
        }
        if (proposeDeployListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            proposeDeployList_ = java.util.Collections.unmodifiableList(proposeDeployList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.proposeDeployList_ = proposeDeployList_;
        } else {
          result.proposeDeployList_ = proposeDeployListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof liubaninc.m0.wasm.Genesis.GenesisState) {
          return mergeFrom((liubaninc.m0.wasm.Genesis.GenesisState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(liubaninc.m0.wasm.Genesis.GenesisState other) {
        if (other == liubaninc.m0.wasm.Genesis.GenesisState.getDefaultInstance()) return this;
        if (other.hasParams()) {
          mergeParams(other.getParams());
        }
        if (approveDeployListBuilder_ == null) {
          if (!other.approveDeployList_.isEmpty()) {
            if (approveDeployList_.isEmpty()) {
              approveDeployList_ = other.approveDeployList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureApproveDeployListIsMutable();
              approveDeployList_.addAll(other.approveDeployList_);
            }
            onChanged();
          }
        } else {
          if (!other.approveDeployList_.isEmpty()) {
            if (approveDeployListBuilder_.isEmpty()) {
              approveDeployListBuilder_.dispose();
              approveDeployListBuilder_ = null;
              approveDeployList_ = other.approveDeployList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              approveDeployListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getApproveDeployListFieldBuilder() : null;
            } else {
              approveDeployListBuilder_.addAllMessages(other.approveDeployList_);
            }
          }
        }
        if (proposeDeployListBuilder_ == null) {
          if (!other.proposeDeployList_.isEmpty()) {
            if (proposeDeployList_.isEmpty()) {
              proposeDeployList_ = other.proposeDeployList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureProposeDeployListIsMutable();
              proposeDeployList_.addAll(other.proposeDeployList_);
            }
            onChanged();
          }
        } else {
          if (!other.proposeDeployList_.isEmpty()) {
            if (proposeDeployListBuilder_.isEmpty()) {
              proposeDeployListBuilder_.dispose();
              proposeDeployListBuilder_ = null;
              proposeDeployList_ = other.proposeDeployList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              proposeDeployListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProposeDeployListFieldBuilder() : null;
            } else {
              proposeDeployListBuilder_.addAllMessages(other.proposeDeployList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        liubaninc.m0.wasm.Genesis.GenesisState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (liubaninc.m0.wasm.Genesis.GenesisState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private liubaninc.m0.wasm.Genesis.Params params_;
      private com.google.protobuf.SingleFieldBuilderV3<
          liubaninc.m0.wasm.Genesis.Params, liubaninc.m0.wasm.Genesis.Params.Builder, liubaninc.m0.wasm.Genesis.ParamsOrBuilder> paramsBuilder_;
      /**
       * <pre>
       * params defines all the paramaters of the module.
       * </pre>
       *
       * <code>.liubaninc.m0.wasm.Params params = 3 [(.gogoproto.nullable) = false];</code>
       */
      public boolean hasParams() {
        return paramsBuilder_ != null || params_ != null;
      }
      /**
       * <pre>
       * params defines all the paramaters of the module.
       * </pre>
       *
       * <code>.liubaninc.m0.wasm.Params params = 3 [(.gogoproto.nullable) = false];</code>
       */
      public liubaninc.m0.wasm.Genesis.Params getParams() {
        if (paramsBuilder_ == null) {
          return params_ == null ? liubaninc.m0.wasm.Genesis.Params.getDefaultInstance() : params_;
        } else {
          return paramsBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * params defines all the paramaters of the module.
       * </pre>
       *
       * <code>.liubaninc.m0.wasm.Params params = 3 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setParams(liubaninc.m0.wasm.Genesis.Params value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          params_ = value;
          onChanged();
        } else {
          paramsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * params defines all the paramaters of the module.
       * </pre>
       *
       * <code>.liubaninc.m0.wasm.Params params = 3 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setParams(
          liubaninc.m0.wasm.Genesis.Params.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          params_ = builderForValue.build();
          onChanged();
        } else {
          paramsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * params defines all the paramaters of the module.
       * </pre>
       *
       * <code>.liubaninc.m0.wasm.Params params = 3 [(.gogoproto.nullable) = false];</code>
       */
      public Builder mergeParams(liubaninc.m0.wasm.Genesis.Params value) {
        if (paramsBuilder_ == null) {
          if (params_ != null) {
            params_ =
              liubaninc.m0.wasm.Genesis.Params.newBuilder(params_).mergeFrom(value).buildPartial();
          } else {
            params_ = value;
          }
          onChanged();
        } else {
          paramsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * params defines all the paramaters of the module.
       * </pre>
       *
       * <code>.liubaninc.m0.wasm.Params params = 3 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearParams() {
        if (paramsBuilder_ == null) {
          params_ = null;
          onChanged();
        } else {
          params_ = null;
          paramsBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * params defines all the paramaters of the module.
       * </pre>
       *
       * <code>.liubaninc.m0.wasm.Params params = 3 [(.gogoproto.nullable) = false];</code>
       */
      public liubaninc.m0.wasm.Genesis.Params.Builder getParamsBuilder() {
        
        onChanged();
        return getParamsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * params defines all the paramaters of the module.
       * </pre>
       *
       * <code>.liubaninc.m0.wasm.Params params = 3 [(.gogoproto.nullable) = false];</code>
       */
      public liubaninc.m0.wasm.Genesis.ParamsOrBuilder getParamsOrBuilder() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilder();
        } else {
          return params_ == null ?
              liubaninc.m0.wasm.Genesis.Params.getDefaultInstance() : params_;
        }
      }
      /**
       * <pre>
       * params defines all the paramaters of the module.
       * </pre>
       *
       * <code>.liubaninc.m0.wasm.Params params = 3 [(.gogoproto.nullable) = false];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          liubaninc.m0.wasm.Genesis.Params, liubaninc.m0.wasm.Genesis.Params.Builder, liubaninc.m0.wasm.Genesis.ParamsOrBuilder> 
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              liubaninc.m0.wasm.Genesis.Params, liubaninc.m0.wasm.Genesis.Params.Builder, liubaninc.m0.wasm.Genesis.ParamsOrBuilder>(
                  getParams(),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }

      private java.util.List<liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy> approveDeployList_ =
        java.util.Collections.emptyList();
      private void ensureApproveDeployListIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          approveDeployList_ = new java.util.ArrayList<liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy>(approveDeployList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy, liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy.Builder, liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeployOrBuilder> approveDeployListBuilder_;

      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public java.util.List<liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy> getApproveDeployListList() {
        if (approveDeployListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(approveDeployList_);
        } else {
          return approveDeployListBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public int getApproveDeployListCount() {
        if (approveDeployListBuilder_ == null) {
          return approveDeployList_.size();
        } else {
          return approveDeployListBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy getApproveDeployList(int index) {
        if (approveDeployListBuilder_ == null) {
          return approveDeployList_.get(index);
        } else {
          return approveDeployListBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public Builder setApproveDeployList(
          int index, liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy value) {
        if (approveDeployListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureApproveDeployListIsMutable();
          approveDeployList_.set(index, value);
          onChanged();
        } else {
          approveDeployListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public Builder setApproveDeployList(
          int index, liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy.Builder builderForValue) {
        if (approveDeployListBuilder_ == null) {
          ensureApproveDeployListIsMutable();
          approveDeployList_.set(index, builderForValue.build());
          onChanged();
        } else {
          approveDeployListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public Builder addApproveDeployList(liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy value) {
        if (approveDeployListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureApproveDeployListIsMutable();
          approveDeployList_.add(value);
          onChanged();
        } else {
          approveDeployListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public Builder addApproveDeployList(
          int index, liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy value) {
        if (approveDeployListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureApproveDeployListIsMutable();
          approveDeployList_.add(index, value);
          onChanged();
        } else {
          approveDeployListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public Builder addApproveDeployList(
          liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy.Builder builderForValue) {
        if (approveDeployListBuilder_ == null) {
          ensureApproveDeployListIsMutable();
          approveDeployList_.add(builderForValue.build());
          onChanged();
        } else {
          approveDeployListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public Builder addApproveDeployList(
          int index, liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy.Builder builderForValue) {
        if (approveDeployListBuilder_ == null) {
          ensureApproveDeployListIsMutable();
          approveDeployList_.add(index, builderForValue.build());
          onChanged();
        } else {
          approveDeployListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public Builder addAllApproveDeployList(
          java.lang.Iterable<? extends liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy> values) {
        if (approveDeployListBuilder_ == null) {
          ensureApproveDeployListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, approveDeployList_);
          onChanged();
        } else {
          approveDeployListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public Builder clearApproveDeployList() {
        if (approveDeployListBuilder_ == null) {
          approveDeployList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          approveDeployListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public Builder removeApproveDeployList(int index) {
        if (approveDeployListBuilder_ == null) {
          ensureApproveDeployListIsMutable();
          approveDeployList_.remove(index);
          onChanged();
        } else {
          approveDeployListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy.Builder getApproveDeployListBuilder(
          int index) {
        return getApproveDeployListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeployOrBuilder getApproveDeployListOrBuilder(
          int index) {
        if (approveDeployListBuilder_ == null) {
          return approveDeployList_.get(index);  } else {
          return approveDeployListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public java.util.List<? extends liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeployOrBuilder> 
           getApproveDeployListOrBuilderList() {
        if (approveDeployListBuilder_ != null) {
          return approveDeployListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(approveDeployList_);
        }
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy.Builder addApproveDeployListBuilder() {
        return getApproveDeployListFieldBuilder().addBuilder(
            liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy.getDefaultInstance());
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy.Builder addApproveDeployListBuilder(
          int index) {
        return getApproveDeployListFieldBuilder().addBuilder(
            index, liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy.getDefaultInstance());
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/state
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ApproveDeploy approveDeployList = 2;</code>
       */
      public java.util.List<liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy.Builder> 
           getApproveDeployListBuilderList() {
        return getApproveDeployListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy, liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy.Builder, liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeployOrBuilder> 
          getApproveDeployListFieldBuilder() {
        if (approveDeployListBuilder_ == null) {
          approveDeployListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy, liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeploy.Builder, liubaninc.m0.wasm.ApproveDeployOuterClass.ApproveDeployOrBuilder>(
                  approveDeployList_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          approveDeployList_ = null;
        }
        return approveDeployListBuilder_;
      }

      private java.util.List<liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy> proposeDeployList_ =
        java.util.Collections.emptyList();
      private void ensureProposeDeployListIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          proposeDeployList_ = new java.util.ArrayList<liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy>(proposeDeployList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy, liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy.Builder, liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeployOrBuilder> proposeDeployListBuilder_;

      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public java.util.List<liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy> getProposeDeployListList() {
        if (proposeDeployListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(proposeDeployList_);
        } else {
          return proposeDeployListBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public int getProposeDeployListCount() {
        if (proposeDeployListBuilder_ == null) {
          return proposeDeployList_.size();
        } else {
          return proposeDeployListBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy getProposeDeployList(int index) {
        if (proposeDeployListBuilder_ == null) {
          return proposeDeployList_.get(index);
        } else {
          return proposeDeployListBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public Builder setProposeDeployList(
          int index, liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy value) {
        if (proposeDeployListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProposeDeployListIsMutable();
          proposeDeployList_.set(index, value);
          onChanged();
        } else {
          proposeDeployListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public Builder setProposeDeployList(
          int index, liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy.Builder builderForValue) {
        if (proposeDeployListBuilder_ == null) {
          ensureProposeDeployListIsMutable();
          proposeDeployList_.set(index, builderForValue.build());
          onChanged();
        } else {
          proposeDeployListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public Builder addProposeDeployList(liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy value) {
        if (proposeDeployListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProposeDeployListIsMutable();
          proposeDeployList_.add(value);
          onChanged();
        } else {
          proposeDeployListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public Builder addProposeDeployList(
          int index, liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy value) {
        if (proposeDeployListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProposeDeployListIsMutable();
          proposeDeployList_.add(index, value);
          onChanged();
        } else {
          proposeDeployListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public Builder addProposeDeployList(
          liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy.Builder builderForValue) {
        if (proposeDeployListBuilder_ == null) {
          ensureProposeDeployListIsMutable();
          proposeDeployList_.add(builderForValue.build());
          onChanged();
        } else {
          proposeDeployListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public Builder addProposeDeployList(
          int index, liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy.Builder builderForValue) {
        if (proposeDeployListBuilder_ == null) {
          ensureProposeDeployListIsMutable();
          proposeDeployList_.add(index, builderForValue.build());
          onChanged();
        } else {
          proposeDeployListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public Builder addAllProposeDeployList(
          java.lang.Iterable<? extends liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy> values) {
        if (proposeDeployListBuilder_ == null) {
          ensureProposeDeployListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, proposeDeployList_);
          onChanged();
        } else {
          proposeDeployListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public Builder clearProposeDeployList() {
        if (proposeDeployListBuilder_ == null) {
          proposeDeployList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          proposeDeployListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public Builder removeProposeDeployList(int index) {
        if (proposeDeployListBuilder_ == null) {
          ensureProposeDeployListIsMutable();
          proposeDeployList_.remove(index);
          onChanged();
        } else {
          proposeDeployListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy.Builder getProposeDeployListBuilder(
          int index) {
        return getProposeDeployListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeployOrBuilder getProposeDeployListOrBuilder(
          int index) {
        if (proposeDeployListBuilder_ == null) {
          return proposeDeployList_.get(index);  } else {
          return proposeDeployListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public java.util.List<? extends liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeployOrBuilder> 
           getProposeDeployListOrBuilderList() {
        if (proposeDeployListBuilder_ != null) {
          return proposeDeployListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(proposeDeployList_);
        }
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy.Builder addProposeDeployListBuilder() {
        return getProposeDeployListFieldBuilder().addBuilder(
            liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy.getDefaultInstance());
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy.Builder addProposeDeployListBuilder(
          int index) {
        return getProposeDeployListFieldBuilder().addBuilder(
            index, liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy.getDefaultInstance());
      }
      /**
       * <pre>
       * this line is used by starport scaffolding # genesis/proto/stateField
       * </pre>
       *
       * <code>repeated .liubaninc.m0.wasm.ProposeDeploy proposeDeployList = 1;</code>
       */
      public java.util.List<liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy.Builder> 
           getProposeDeployListBuilderList() {
        return getProposeDeployListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy, liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy.Builder, liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeployOrBuilder> 
          getProposeDeployListFieldBuilder() {
        if (proposeDeployListBuilder_ == null) {
          proposeDeployListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy, liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeploy.Builder, liubaninc.m0.wasm.ProposeDeployOuterClass.ProposeDeployOrBuilder>(
                  proposeDeployList_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          proposeDeployList_ = null;
        }
        return proposeDeployListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:liubaninc.m0.wasm.GenesisState)
    }

    // @@protoc_insertion_point(class_scope:liubaninc.m0.wasm.GenesisState)
    private static final liubaninc.m0.wasm.Genesis.GenesisState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new liubaninc.m0.wasm.Genesis.GenesisState();
    }

    public static liubaninc.m0.wasm.Genesis.GenesisState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenesisState>
        PARSER = new com.google.protobuf.AbstractParser<GenesisState>() {
      @java.lang.Override
      public GenesisState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GenesisState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GenesisState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenesisState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public liubaninc.m0.wasm.Genesis.GenesisState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:liubaninc.m0.wasm.Params)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool enabled = 2 [(.gogoproto.moretags) = "yaml:&#92;"enabled,omitempty&#92;""];</code>
     */
    boolean getEnabled();
  }
  /**
   * <pre>
   * Params defines the parameters for the module.
   * </pre>
   *
   * Protobuf type {@code liubaninc.m0.wasm.Params}
   */
  public  static final class Params extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:liubaninc.m0.wasm.Params)
      ParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Params.newBuilder() to construct.
    private Params(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Params() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Params(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {

              enabled_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return liubaninc.m0.wasm.Genesis.internal_static_liubaninc_m0_wasm_Params_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return liubaninc.m0.wasm.Genesis.internal_static_liubaninc_m0_wasm_Params_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              liubaninc.m0.wasm.Genesis.Params.class, liubaninc.m0.wasm.Genesis.Params.Builder.class);
    }

    public static final int ENABLED_FIELD_NUMBER = 2;
    private boolean enabled_;
    /**
     * <code>bool enabled = 2 [(.gogoproto.moretags) = "yaml:&#92;"enabled,omitempty&#92;""];</code>
     */
    public boolean getEnabled() {
      return enabled_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (enabled_ != false) {
        output.writeBool(2, enabled_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (enabled_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, enabled_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof liubaninc.m0.wasm.Genesis.Params)) {
        return super.equals(obj);
      }
      liubaninc.m0.wasm.Genesis.Params other = (liubaninc.m0.wasm.Genesis.Params) obj;

      if (getEnabled()
          != other.getEnabled()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENABLED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEnabled());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static liubaninc.m0.wasm.Genesis.Params parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static liubaninc.m0.wasm.Genesis.Params parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static liubaninc.m0.wasm.Genesis.Params parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static liubaninc.m0.wasm.Genesis.Params parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static liubaninc.m0.wasm.Genesis.Params parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static liubaninc.m0.wasm.Genesis.Params parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static liubaninc.m0.wasm.Genesis.Params parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static liubaninc.m0.wasm.Genesis.Params parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static liubaninc.m0.wasm.Genesis.Params parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static liubaninc.m0.wasm.Genesis.Params parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static liubaninc.m0.wasm.Genesis.Params parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static liubaninc.m0.wasm.Genesis.Params parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(liubaninc.m0.wasm.Genesis.Params prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Params defines the parameters for the module.
     * </pre>
     *
     * Protobuf type {@code liubaninc.m0.wasm.Params}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:liubaninc.m0.wasm.Params)
        liubaninc.m0.wasm.Genesis.ParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return liubaninc.m0.wasm.Genesis.internal_static_liubaninc_m0_wasm_Params_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return liubaninc.m0.wasm.Genesis.internal_static_liubaninc_m0_wasm_Params_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                liubaninc.m0.wasm.Genesis.Params.class, liubaninc.m0.wasm.Genesis.Params.Builder.class);
      }

      // Construct using liubaninc.m0.wasm.Genesis.Params.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        enabled_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return liubaninc.m0.wasm.Genesis.internal_static_liubaninc_m0_wasm_Params_descriptor;
      }

      @java.lang.Override
      public liubaninc.m0.wasm.Genesis.Params getDefaultInstanceForType() {
        return liubaninc.m0.wasm.Genesis.Params.getDefaultInstance();
      }

      @java.lang.Override
      public liubaninc.m0.wasm.Genesis.Params build() {
        liubaninc.m0.wasm.Genesis.Params result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public liubaninc.m0.wasm.Genesis.Params buildPartial() {
        liubaninc.m0.wasm.Genesis.Params result = new liubaninc.m0.wasm.Genesis.Params(this);
        result.enabled_ = enabled_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof liubaninc.m0.wasm.Genesis.Params) {
          return mergeFrom((liubaninc.m0.wasm.Genesis.Params)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(liubaninc.m0.wasm.Genesis.Params other) {
        if (other == liubaninc.m0.wasm.Genesis.Params.getDefaultInstance()) return this;
        if (other.getEnabled() != false) {
          setEnabled(other.getEnabled());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        liubaninc.m0.wasm.Genesis.Params parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (liubaninc.m0.wasm.Genesis.Params) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean enabled_ ;
      /**
       * <code>bool enabled = 2 [(.gogoproto.moretags) = "yaml:&#92;"enabled,omitempty&#92;""];</code>
       */
      public boolean getEnabled() {
        return enabled_;
      }
      /**
       * <code>bool enabled = 2 [(.gogoproto.moretags) = "yaml:&#92;"enabled,omitempty&#92;""];</code>
       */
      public Builder setEnabled(boolean value) {
        
        enabled_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool enabled = 2 [(.gogoproto.moretags) = "yaml:&#92;"enabled,omitempty&#92;""];</code>
       */
      public Builder clearEnabled() {
        
        enabled_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:liubaninc.m0.wasm.Params)
    }

    // @@protoc_insertion_point(class_scope:liubaninc.m0.wasm.Params)
    private static final liubaninc.m0.wasm.Genesis.Params DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new liubaninc.m0.wasm.Genesis.Params();
    }

    public static liubaninc.m0.wasm.Genesis.Params getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Params>
        PARSER = new com.google.protobuf.AbstractParser<Params>() {
      @java.lang.Override
      public Params parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Params(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Params> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Params> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public liubaninc.m0.wasm.Genesis.Params getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_liubaninc_m0_wasm_GenesisState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_liubaninc_m0_wasm_GenesisState_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_liubaninc_m0_wasm_Params_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_liubaninc_m0_wasm_Params_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025m0/wasm/genesis.proto\022\021liubaninc.m0.wa" +
      "sm\032\024gogoproto/gogo.proto\032\034m0/wasm/approv" +
      "e_deploy.proto\032\034m0/wasm/propose_deploy.p" +
      "roto\"\271\001\n\014GenesisState\022/\n\006params\030\003 \001(\0132\031." +
      "liubaninc.m0.wasm.ParamsB\004\310\336\037\000\022;\n\021approv" +
      "eDeployList\030\002 \003(\0132 .liubaninc.m0.wasm.Ap" +
      "proveDeploy\022;\n\021proposeDeployList\030\001 \003(\0132 " +
      ".liubaninc.m0.wasm.ProposeDeploy\"=\n\006Para" +
      "ms\022-\n\007enabled\030\002 \001(\010B\034\362\336\037\030yaml:\"enabled,o" +
      "mitempty\":\004\230\240\037\000B&Z$github.com/liubaninc/" +
      "m0/x/wasm/typesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          liubaninc.m0.wasm.ApproveDeployOuterClass.getDescriptor(),
          liubaninc.m0.wasm.ProposeDeployOuterClass.getDescriptor(),
        }, assigner);
    internal_static_liubaninc_m0_wasm_GenesisState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_liubaninc_m0_wasm_GenesisState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_liubaninc_m0_wasm_GenesisState_descriptor,
        new java.lang.String[] { "Params", "ApproveDeployList", "ProposeDeployList", });
    internal_static_liubaninc_m0_wasm_Params_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_liubaninc_m0_wasm_Params_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_liubaninc_m0_wasm_Params_descriptor,
        new java.lang.String[] { "Enabled", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.goprotoStringer);
    registry.add(com.google.protobuf.GoGoProtos.moretags);
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
    liubaninc.m0.wasm.ApproveDeployOuterClass.getDescriptor();
    liubaninc.m0.wasm.ProposeDeployOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
