// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: m0/validator/last_validator_power.proto

package liubaninc.m0.validator;

public final class LastValidatorPowerOuterClass {
  private LastValidatorPowerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LastValidatorPowerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:liubaninc.m0.validator.LastValidatorPower)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string index = 2;</code>
     */
    java.lang.String getIndex();
    /**
     * <code>string index = 2;</code>
     */
    com.google.protobuf.ByteString
        getIndexBytes();

    /**
     * <code>int64 power = 3;</code>
     */
    long getPower();
  }
  /**
   * Protobuf type {@code liubaninc.m0.validator.LastValidatorPower}
   */
  public  static final class LastValidatorPower extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:liubaninc.m0.validator.LastValidatorPower)
      LastValidatorPowerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LastValidatorPower.newBuilder() to construct.
    private LastValidatorPower(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LastValidatorPower() {
      index_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LastValidatorPower(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              index_ = s;
              break;
            }
            case 24: {

              power_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return liubaninc.m0.validator.LastValidatorPowerOuterClass.internal_static_liubaninc_m0_validator_LastValidatorPower_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return liubaninc.m0.validator.LastValidatorPowerOuterClass.internal_static_liubaninc_m0_validator_LastValidatorPower_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower.class, liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 2;
    private volatile java.lang.Object index_;
    /**
     * <code>string index = 2;</code>
     */
    public java.lang.String getIndex() {
      java.lang.Object ref = index_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        index_ = s;
        return s;
      }
    }
    /**
     * <code>string index = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIndexBytes() {
      java.lang.Object ref = index_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        index_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POWER_FIELD_NUMBER = 3;
    private long power_;
    /**
     * <code>int64 power = 3;</code>
     */
    public long getPower() {
      return power_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIndexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, index_);
      }
      if (power_ != 0L) {
        output.writeInt64(3, power_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIndexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, index_);
      }
      if (power_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, power_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower)) {
        return super.equals(obj);
      }
      liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower other = (liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower) obj;

      if (!getIndex()
          .equals(other.getIndex())) return false;
      if (getPower()
          != other.getPower()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex().hashCode();
      hash = (37 * hash) + POWER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPower());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code liubaninc.m0.validator.LastValidatorPower}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:liubaninc.m0.validator.LastValidatorPower)
        liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPowerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return liubaninc.m0.validator.LastValidatorPowerOuterClass.internal_static_liubaninc_m0_validator_LastValidatorPower_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return liubaninc.m0.validator.LastValidatorPowerOuterClass.internal_static_liubaninc_m0_validator_LastValidatorPower_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower.class, liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower.Builder.class);
      }

      // Construct using liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        index_ = "";

        power_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return liubaninc.m0.validator.LastValidatorPowerOuterClass.internal_static_liubaninc_m0_validator_LastValidatorPower_descriptor;
      }

      @java.lang.Override
      public liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower getDefaultInstanceForType() {
        return liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower.getDefaultInstance();
      }

      @java.lang.Override
      public liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower build() {
        liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower buildPartial() {
        liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower result = new liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower(this);
        result.index_ = index_;
        result.power_ = power_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower) {
          return mergeFrom((liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower other) {
        if (other == liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower.getDefaultInstance()) return this;
        if (!other.getIndex().isEmpty()) {
          index_ = other.index_;
          onChanged();
        }
        if (other.getPower() != 0L) {
          setPower(other.getPower());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object index_ = "";
      /**
       * <code>string index = 2;</code>
       */
      public java.lang.String getIndex() {
        java.lang.Object ref = index_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          index_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string index = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIndexBytes() {
        java.lang.Object ref = index_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          index_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string index = 2;</code>
       */
      public Builder setIndex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string index = 2;</code>
       */
      public Builder clearIndex() {
        
        index_ = getDefaultInstance().getIndex();
        onChanged();
        return this;
      }
      /**
       * <code>string index = 2;</code>
       */
      public Builder setIndexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        index_ = value;
        onChanged();
        return this;
      }

      private long power_ ;
      /**
       * <code>int64 power = 3;</code>
       */
      public long getPower() {
        return power_;
      }
      /**
       * <code>int64 power = 3;</code>
       */
      public Builder setPower(long value) {
        
        power_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 power = 3;</code>
       */
      public Builder clearPower() {
        
        power_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:liubaninc.m0.validator.LastValidatorPower)
    }

    // @@protoc_insertion_point(class_scope:liubaninc.m0.validator.LastValidatorPower)
    private static final liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower();
    }

    public static liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LastValidatorPower>
        PARSER = new com.google.protobuf.AbstractParser<LastValidatorPower>() {
      @java.lang.Override
      public LastValidatorPower parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LastValidatorPower(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LastValidatorPower> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LastValidatorPower> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public liubaninc.m0.validator.LastValidatorPowerOuterClass.LastValidatorPower getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_liubaninc_m0_validator_LastValidatorPower_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_liubaninc_m0_validator_LastValidatorPower_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'m0/validator/last_validator_power.prot" +
      "o\022\026liubaninc.m0.validator\"2\n\022LastValidat" +
      "orPower\022\r\n\005index\030\002 \001(\t\022\r\n\005power\030\003 \001(\003B+Z" +
      ")github.com/liubaninc/m0/x/validator/typ" +
      "esb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_liubaninc_m0_validator_LastValidatorPower_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_liubaninc_m0_validator_LastValidatorPower_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_liubaninc_m0_validator_LastValidatorPower_descriptor,
        new java.lang.String[] { "Index", "Power", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
