version: '2.4'

volumes:
  mytestnet:
  mysql:

networks:
  test:
    name: m0_test

services:
  m0-mysql:
    container_name: m0-mysql
    image: mysql:latest
    labels:
      service: tq-m0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=m0
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - test

  # m0区块链
  m0-node0:
    container_name: m0-node0
    image: liubaninc/m0:${TAG}
    # restart: always
    labels:
      service: tq-m0
    environment:
      - M0D_CHAIN_ID=testchain
      - M0D_GENESIS_TIME=1615183366
      - M0D_CONSENSUS_CREATE_EMPTY_BLOCKS=true
      - M0D_HOME=/var/tq/production/mytestnet/node0/.m0
      - M0D_LOG_FORMAT=json
      - M0D_LOG_LEVEL=info
      - M0D_INSTRUMENTATION_PROMETHEUS=true
    command:
      - "sh"
      - "-c"
      - |
        set -ex
        if [ ! -e $M0D_HOME/config/genesis.json ]; then
        m0d testnet -n 1
        cp -r mytestnet /var/tq/production
        fi
        m0d start --pruning nothing
    volumes:
      - mytestnet:/var/tq/production/mytestnet
    ports:
      - 26661:26660
      - 26666:26656
      - 26667:26657
    networks:
      - test

  # m0自动发送交易
  m0-automatic:
    container_name: m0-automatic
    image: liubaninc/m0:${TAG}
    # restart: always
    labels:
      service: tq-m0
    environment:
      - M0D_CHAIN_ID=testchain
      - WAIT_HOSTS=m0-node0:26657
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    command:
      - "sh"
      - "-c"
      - |
        /wait
        /automatic.sh
    volumes:
      - mytestnet:/var/tq/production/mytestnet
    depends_on:
      - m0-node0
      - m0-mysql
    networks:
      - test

  # m0区块数据同步
  m0-synced:
    container_name: m0-synced
    image: liubaninc/m0:${TAG}
    # restart: always
    labels:
      service: tq-m0
    environment:
      - SYNCED_HOME=/var/tq/production/mytestnet/
      - SYNCED_DB_HOST=m0-mysql
      - SYNCED_NODE_RPC=tcp://m0-node0:26657
      - WAIT_HOSTS=m0-mysql:3306,m0-node0:26657
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    command: 
      - "sh" 
      - "-c" 
      - |
        /wait
        /synced.sh
    volumes:
      - mytestnet:/var/tq/production/mytestnet
    depends_on:
      - m0-node0
      - m0-mysql
    ports:
      - 8081:8086
      - 8082:8088
      - 8089:8080
    networks:
      - test