// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: m0/utxo/input.proto

package liubaninc.m0.utxo;

public final class InputOuterClass {
  private InputOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:liubaninc.m0.utxo.Input)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ref_tx = 1;</code>
     */
    java.lang.String getRefTx();
    /**
     * <code>string ref_tx = 1;</code>
     */
    com.google.protobuf.ByteString
        getRefTxBytes();

    /**
     * <code>int32 ref_msg = 2;</code>
     */
    int getRefMsg();

    /**
     * <code>int32 ref_offset = 3;</code>
     */
    int getRefOffset();

    /**
     * <code>string from_addr = 4;</code>
     */
    java.lang.String getFromAddr();
    /**
     * <code>string from_addr = 4;</code>
     */
    com.google.protobuf.ByteString
        getFromAddrBytes();

    /**
     * <code>.cosmos.base.v1beta1.Coin amount = 5 [(.gogoproto.nullable) = false];</code>
     */
    boolean hasAmount();
    /**
     * <code>.cosmos.base.v1beta1.Coin amount = 5 [(.gogoproto.nullable) = false];</code>
     */
    cosmos.base.v1beta1.CoinOuterClass.Coin getAmount();
    /**
     * <code>.cosmos.base.v1beta1.Coin amount = 5 [(.gogoproto.nullable) = false];</code>
     */
    cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getAmountOrBuilder();

    /**
     * <code>int64 frozen_height = 7;</code>
     */
    long getFrozenHeight();
  }
  /**
   * Protobuf type {@code liubaninc.m0.utxo.Input}
   */
  public  static final class Input extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:liubaninc.m0.utxo.Input)
      InputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Input.newBuilder() to construct.
    private Input(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Input() {
      refTx_ = "";
      fromAddr_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Input(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              refTx_ = s;
              break;
            }
            case 16: {

              refMsg_ = input.readInt32();
              break;
            }
            case 24: {

              refOffset_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              fromAddr_ = s;
              break;
            }
            case 42: {
              cosmos.base.v1beta1.CoinOuterClass.Coin.Builder subBuilder = null;
              if (amount_ != null) {
                subBuilder = amount_.toBuilder();
              }
              amount_ = input.readMessage(cosmos.base.v1beta1.CoinOuterClass.Coin.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(amount_);
                amount_ = subBuilder.buildPartial();
              }

              break;
            }
            case 56: {

              frozenHeight_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return liubaninc.m0.utxo.InputOuterClass.internal_static_liubaninc_m0_utxo_Input_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return liubaninc.m0.utxo.InputOuterClass.internal_static_liubaninc_m0_utxo_Input_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              liubaninc.m0.utxo.InputOuterClass.Input.class, liubaninc.m0.utxo.InputOuterClass.Input.Builder.class);
    }

    public static final int REF_TX_FIELD_NUMBER = 1;
    private volatile java.lang.Object refTx_;
    /**
     * <code>string ref_tx = 1;</code>
     */
    public java.lang.String getRefTx() {
      java.lang.Object ref = refTx_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refTx_ = s;
        return s;
      }
    }
    /**
     * <code>string ref_tx = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRefTxBytes() {
      java.lang.Object ref = refTx_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refTx_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REF_MSG_FIELD_NUMBER = 2;
    private int refMsg_;
    /**
     * <code>int32 ref_msg = 2;</code>
     */
    public int getRefMsg() {
      return refMsg_;
    }

    public static final int REF_OFFSET_FIELD_NUMBER = 3;
    private int refOffset_;
    /**
     * <code>int32 ref_offset = 3;</code>
     */
    public int getRefOffset() {
      return refOffset_;
    }

    public static final int FROM_ADDR_FIELD_NUMBER = 4;
    private volatile java.lang.Object fromAddr_;
    /**
     * <code>string from_addr = 4;</code>
     */
    public java.lang.String getFromAddr() {
      java.lang.Object ref = fromAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromAddr_ = s;
        return s;
      }
    }
    /**
     * <code>string from_addr = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFromAddrBytes() {
      java.lang.Object ref = fromAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 5;
    private cosmos.base.v1beta1.CoinOuterClass.Coin amount_;
    /**
     * <code>.cosmos.base.v1beta1.Coin amount = 5 [(.gogoproto.nullable) = false];</code>
     */
    public boolean hasAmount() {
      return amount_ != null;
    }
    /**
     * <code>.cosmos.base.v1beta1.Coin amount = 5 [(.gogoproto.nullable) = false];</code>
     */
    public cosmos.base.v1beta1.CoinOuterClass.Coin getAmount() {
      return amount_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : amount_;
    }
    /**
     * <code>.cosmos.base.v1beta1.Coin amount = 5 [(.gogoproto.nullable) = false];</code>
     */
    public cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getAmountOrBuilder() {
      return getAmount();
    }

    public static final int FROZEN_HEIGHT_FIELD_NUMBER = 7;
    private long frozenHeight_;
    /**
     * <code>int64 frozen_height = 7;</code>
     */
    public long getFrozenHeight() {
      return frozenHeight_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRefTxBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, refTx_);
      }
      if (refMsg_ != 0) {
        output.writeInt32(2, refMsg_);
      }
      if (refOffset_ != 0) {
        output.writeInt32(3, refOffset_);
      }
      if (!getFromAddrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromAddr_);
      }
      if (amount_ != null) {
        output.writeMessage(5, getAmount());
      }
      if (frozenHeight_ != 0L) {
        output.writeInt64(7, frozenHeight_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRefTxBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, refTx_);
      }
      if (refMsg_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, refMsg_);
      }
      if (refOffset_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, refOffset_);
      }
      if (!getFromAddrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromAddr_);
      }
      if (amount_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getAmount());
      }
      if (frozenHeight_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, frozenHeight_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof liubaninc.m0.utxo.InputOuterClass.Input)) {
        return super.equals(obj);
      }
      liubaninc.m0.utxo.InputOuterClass.Input other = (liubaninc.m0.utxo.InputOuterClass.Input) obj;

      if (!getRefTx()
          .equals(other.getRefTx())) return false;
      if (getRefMsg()
          != other.getRefMsg()) return false;
      if (getRefOffset()
          != other.getRefOffset()) return false;
      if (!getFromAddr()
          .equals(other.getFromAddr())) return false;
      if (hasAmount() != other.hasAmount()) return false;
      if (hasAmount()) {
        if (!getAmount()
            .equals(other.getAmount())) return false;
      }
      if (getFrozenHeight()
          != other.getFrozenHeight()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REF_TX_FIELD_NUMBER;
      hash = (53 * hash) + getRefTx().hashCode();
      hash = (37 * hash) + REF_MSG_FIELD_NUMBER;
      hash = (53 * hash) + getRefMsg();
      hash = (37 * hash) + REF_OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getRefOffset();
      hash = (37 * hash) + FROM_ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getFromAddr().hashCode();
      if (hasAmount()) {
        hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAmount().hashCode();
      }
      hash = (37 * hash) + FROZEN_HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFrozenHeight());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static liubaninc.m0.utxo.InputOuterClass.Input parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Input parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Input parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Input parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Input parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Input parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Input parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Input parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Input parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Input parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Input parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Input parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(liubaninc.m0.utxo.InputOuterClass.Input prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code liubaninc.m0.utxo.Input}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:liubaninc.m0.utxo.Input)
        liubaninc.m0.utxo.InputOuterClass.InputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return liubaninc.m0.utxo.InputOuterClass.internal_static_liubaninc_m0_utxo_Input_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return liubaninc.m0.utxo.InputOuterClass.internal_static_liubaninc_m0_utxo_Input_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                liubaninc.m0.utxo.InputOuterClass.Input.class, liubaninc.m0.utxo.InputOuterClass.Input.Builder.class);
      }

      // Construct using liubaninc.m0.utxo.InputOuterClass.Input.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        refTx_ = "";

        refMsg_ = 0;

        refOffset_ = 0;

        fromAddr_ = "";

        if (amountBuilder_ == null) {
          amount_ = null;
        } else {
          amount_ = null;
          amountBuilder_ = null;
        }
        frozenHeight_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return liubaninc.m0.utxo.InputOuterClass.internal_static_liubaninc_m0_utxo_Input_descriptor;
      }

      @java.lang.Override
      public liubaninc.m0.utxo.InputOuterClass.Input getDefaultInstanceForType() {
        return liubaninc.m0.utxo.InputOuterClass.Input.getDefaultInstance();
      }

      @java.lang.Override
      public liubaninc.m0.utxo.InputOuterClass.Input build() {
        liubaninc.m0.utxo.InputOuterClass.Input result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public liubaninc.m0.utxo.InputOuterClass.Input buildPartial() {
        liubaninc.m0.utxo.InputOuterClass.Input result = new liubaninc.m0.utxo.InputOuterClass.Input(this);
        result.refTx_ = refTx_;
        result.refMsg_ = refMsg_;
        result.refOffset_ = refOffset_;
        result.fromAddr_ = fromAddr_;
        if (amountBuilder_ == null) {
          result.amount_ = amount_;
        } else {
          result.amount_ = amountBuilder_.build();
        }
        result.frozenHeight_ = frozenHeight_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof liubaninc.m0.utxo.InputOuterClass.Input) {
          return mergeFrom((liubaninc.m0.utxo.InputOuterClass.Input)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(liubaninc.m0.utxo.InputOuterClass.Input other) {
        if (other == liubaninc.m0.utxo.InputOuterClass.Input.getDefaultInstance()) return this;
        if (!other.getRefTx().isEmpty()) {
          refTx_ = other.refTx_;
          onChanged();
        }
        if (other.getRefMsg() != 0) {
          setRefMsg(other.getRefMsg());
        }
        if (other.getRefOffset() != 0) {
          setRefOffset(other.getRefOffset());
        }
        if (!other.getFromAddr().isEmpty()) {
          fromAddr_ = other.fromAddr_;
          onChanged();
        }
        if (other.hasAmount()) {
          mergeAmount(other.getAmount());
        }
        if (other.getFrozenHeight() != 0L) {
          setFrozenHeight(other.getFrozenHeight());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        liubaninc.m0.utxo.InputOuterClass.Input parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (liubaninc.m0.utxo.InputOuterClass.Input) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object refTx_ = "";
      /**
       * <code>string ref_tx = 1;</code>
       */
      public java.lang.String getRefTx() {
        java.lang.Object ref = refTx_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          refTx_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ref_tx = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRefTxBytes() {
        java.lang.Object ref = refTx_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          refTx_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ref_tx = 1;</code>
       */
      public Builder setRefTx(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        refTx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ref_tx = 1;</code>
       */
      public Builder clearRefTx() {
        
        refTx_ = getDefaultInstance().getRefTx();
        onChanged();
        return this;
      }
      /**
       * <code>string ref_tx = 1;</code>
       */
      public Builder setRefTxBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        refTx_ = value;
        onChanged();
        return this;
      }

      private int refMsg_ ;
      /**
       * <code>int32 ref_msg = 2;</code>
       */
      public int getRefMsg() {
        return refMsg_;
      }
      /**
       * <code>int32 ref_msg = 2;</code>
       */
      public Builder setRefMsg(int value) {
        
        refMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ref_msg = 2;</code>
       */
      public Builder clearRefMsg() {
        
        refMsg_ = 0;
        onChanged();
        return this;
      }

      private int refOffset_ ;
      /**
       * <code>int32 ref_offset = 3;</code>
       */
      public int getRefOffset() {
        return refOffset_;
      }
      /**
       * <code>int32 ref_offset = 3;</code>
       */
      public Builder setRefOffset(int value) {
        
        refOffset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ref_offset = 3;</code>
       */
      public Builder clearRefOffset() {
        
        refOffset_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fromAddr_ = "";
      /**
       * <code>string from_addr = 4;</code>
       */
      public java.lang.String getFromAddr() {
        java.lang.Object ref = fromAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromAddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string from_addr = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFromAddrBytes() {
        java.lang.Object ref = fromAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string from_addr = 4;</code>
       */
      public Builder setFromAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string from_addr = 4;</code>
       */
      public Builder clearFromAddr() {
        
        fromAddr_ = getDefaultInstance().getFromAddr();
        onChanged();
        return this;
      }
      /**
       * <code>string from_addr = 4;</code>
       */
      public Builder setFromAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromAddr_ = value;
        onChanged();
        return this;
      }

      private cosmos.base.v1beta1.CoinOuterClass.Coin amount_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder> amountBuilder_;
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 5 [(.gogoproto.nullable) = false];</code>
       */
      public boolean hasAmount() {
        return amountBuilder_ != null || amount_ != null;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 5 [(.gogoproto.nullable) = false];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.Coin getAmount() {
        if (amountBuilder_ == null) {
          return amount_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : amount_;
        } else {
          return amountBuilder_.getMessage();
        }
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 5 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setAmount(cosmos.base.v1beta1.CoinOuterClass.Coin value) {
        if (amountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          amount_ = value;
          onChanged();
        } else {
          amountBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 5 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setAmount(
          cosmos.base.v1beta1.CoinOuterClass.Coin.Builder builderForValue) {
        if (amountBuilder_ == null) {
          amount_ = builderForValue.build();
          onChanged();
        } else {
          amountBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 5 [(.gogoproto.nullable) = false];</code>
       */
      public Builder mergeAmount(cosmos.base.v1beta1.CoinOuterClass.Coin value) {
        if (amountBuilder_ == null) {
          if (amount_ != null) {
            amount_ =
              cosmos.base.v1beta1.CoinOuterClass.Coin.newBuilder(amount_).mergeFrom(value).buildPartial();
          } else {
            amount_ = value;
          }
          onChanged();
        } else {
          amountBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 5 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearAmount() {
        if (amountBuilder_ == null) {
          amount_ = null;
          onChanged();
        } else {
          amount_ = null;
          amountBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 5 [(.gogoproto.nullable) = false];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.Coin.Builder getAmountBuilder() {
        
        onChanged();
        return getAmountFieldBuilder().getBuilder();
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 5 [(.gogoproto.nullable) = false];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getAmountOrBuilder() {
        if (amountBuilder_ != null) {
          return amountBuilder_.getMessageOrBuilder();
        } else {
          return amount_ == null ?
              cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : amount_;
        }
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 5 [(.gogoproto.nullable) = false];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder> 
          getAmountFieldBuilder() {
        if (amountBuilder_ == null) {
          amountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder>(
                  getAmount(),
                  getParentForChildren(),
                  isClean());
          amount_ = null;
        }
        return amountBuilder_;
      }

      private long frozenHeight_ ;
      /**
       * <code>int64 frozen_height = 7;</code>
       */
      public long getFrozenHeight() {
        return frozenHeight_;
      }
      /**
       * <code>int64 frozen_height = 7;</code>
       */
      public Builder setFrozenHeight(long value) {
        
        frozenHeight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 frozen_height = 7;</code>
       */
      public Builder clearFrozenHeight() {
        
        frozenHeight_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:liubaninc.m0.utxo.Input)
    }

    // @@protoc_insertion_point(class_scope:liubaninc.m0.utxo.Input)
    private static final liubaninc.m0.utxo.InputOuterClass.Input DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new liubaninc.m0.utxo.InputOuterClass.Input();
    }

    public static liubaninc.m0.utxo.InputOuterClass.Input getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Input>
        PARSER = new com.google.protobuf.AbstractParser<Input>() {
      @java.lang.Override
      public Input parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Input(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Input> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Input> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public liubaninc.m0.utxo.InputOuterClass.Input getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:liubaninc.m0.utxo.Output)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string to_addr = 1;</code>
     */
    java.lang.String getToAddr();
    /**
     * <code>string to_addr = 1;</code>
     */
    com.google.protobuf.ByteString
        getToAddrBytes();

    /**
     * <code>.cosmos.base.v1beta1.Coin amount = 2 [(.gogoproto.nullable) = false];</code>
     */
    boolean hasAmount();
    /**
     * <code>.cosmos.base.v1beta1.Coin amount = 2 [(.gogoproto.nullable) = false];</code>
     */
    cosmos.base.v1beta1.CoinOuterClass.Coin getAmount();
    /**
     * <code>.cosmos.base.v1beta1.Coin amount = 2 [(.gogoproto.nullable) = false];</code>
     */
    cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getAmountOrBuilder();

    /**
     * <code>int64 frozen_height = 4;</code>
     */
    long getFrozenHeight();

    /**
     * <code>bool change = 5;</code>
     */
    boolean getChange();
  }
  /**
   * Protobuf type {@code liubaninc.m0.utxo.Output}
   */
  public  static final class Output extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:liubaninc.m0.utxo.Output)
      OutputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Output.newBuilder() to construct.
    private Output(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Output() {
      toAddr_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Output(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              toAddr_ = s;
              break;
            }
            case 18: {
              cosmos.base.v1beta1.CoinOuterClass.Coin.Builder subBuilder = null;
              if (amount_ != null) {
                subBuilder = amount_.toBuilder();
              }
              amount_ = input.readMessage(cosmos.base.v1beta1.CoinOuterClass.Coin.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(amount_);
                amount_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {

              frozenHeight_ = input.readInt64();
              break;
            }
            case 40: {

              change_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return liubaninc.m0.utxo.InputOuterClass.internal_static_liubaninc_m0_utxo_Output_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return liubaninc.m0.utxo.InputOuterClass.internal_static_liubaninc_m0_utxo_Output_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              liubaninc.m0.utxo.InputOuterClass.Output.class, liubaninc.m0.utxo.InputOuterClass.Output.Builder.class);
    }

    public static final int TO_ADDR_FIELD_NUMBER = 1;
    private volatile java.lang.Object toAddr_;
    /**
     * <code>string to_addr = 1;</code>
     */
    public java.lang.String getToAddr() {
      java.lang.Object ref = toAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toAddr_ = s;
        return s;
      }
    }
    /**
     * <code>string to_addr = 1;</code>
     */
    public com.google.protobuf.ByteString
        getToAddrBytes() {
      java.lang.Object ref = toAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 2;
    private cosmos.base.v1beta1.CoinOuterClass.Coin amount_;
    /**
     * <code>.cosmos.base.v1beta1.Coin amount = 2 [(.gogoproto.nullable) = false];</code>
     */
    public boolean hasAmount() {
      return amount_ != null;
    }
    /**
     * <code>.cosmos.base.v1beta1.Coin amount = 2 [(.gogoproto.nullable) = false];</code>
     */
    public cosmos.base.v1beta1.CoinOuterClass.Coin getAmount() {
      return amount_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : amount_;
    }
    /**
     * <code>.cosmos.base.v1beta1.Coin amount = 2 [(.gogoproto.nullable) = false];</code>
     */
    public cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getAmountOrBuilder() {
      return getAmount();
    }

    public static final int FROZEN_HEIGHT_FIELD_NUMBER = 4;
    private long frozenHeight_;
    /**
     * <code>int64 frozen_height = 4;</code>
     */
    public long getFrozenHeight() {
      return frozenHeight_;
    }

    public static final int CHANGE_FIELD_NUMBER = 5;
    private boolean change_;
    /**
     * <code>bool change = 5;</code>
     */
    public boolean getChange() {
      return change_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getToAddrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, toAddr_);
      }
      if (amount_ != null) {
        output.writeMessage(2, getAmount());
      }
      if (frozenHeight_ != 0L) {
        output.writeInt64(4, frozenHeight_);
      }
      if (change_ != false) {
        output.writeBool(5, change_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getToAddrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, toAddr_);
      }
      if (amount_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getAmount());
      }
      if (frozenHeight_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, frozenHeight_);
      }
      if (change_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, change_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof liubaninc.m0.utxo.InputOuterClass.Output)) {
        return super.equals(obj);
      }
      liubaninc.m0.utxo.InputOuterClass.Output other = (liubaninc.m0.utxo.InputOuterClass.Output) obj;

      if (!getToAddr()
          .equals(other.getToAddr())) return false;
      if (hasAmount() != other.hasAmount()) return false;
      if (hasAmount()) {
        if (!getAmount()
            .equals(other.getAmount())) return false;
      }
      if (getFrozenHeight()
          != other.getFrozenHeight()) return false;
      if (getChange()
          != other.getChange()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TO_ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getToAddr().hashCode();
      if (hasAmount()) {
        hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAmount().hashCode();
      }
      hash = (37 * hash) + FROZEN_HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFrozenHeight());
      hash = (37 * hash) + CHANGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getChange());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static liubaninc.m0.utxo.InputOuterClass.Output parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Output parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Output parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Output parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Output parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Output parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Output parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Output parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Output parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Output parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Output parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static liubaninc.m0.utxo.InputOuterClass.Output parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(liubaninc.m0.utxo.InputOuterClass.Output prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code liubaninc.m0.utxo.Output}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:liubaninc.m0.utxo.Output)
        liubaninc.m0.utxo.InputOuterClass.OutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return liubaninc.m0.utxo.InputOuterClass.internal_static_liubaninc_m0_utxo_Output_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return liubaninc.m0.utxo.InputOuterClass.internal_static_liubaninc_m0_utxo_Output_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                liubaninc.m0.utxo.InputOuterClass.Output.class, liubaninc.m0.utxo.InputOuterClass.Output.Builder.class);
      }

      // Construct using liubaninc.m0.utxo.InputOuterClass.Output.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        toAddr_ = "";

        if (amountBuilder_ == null) {
          amount_ = null;
        } else {
          amount_ = null;
          amountBuilder_ = null;
        }
        frozenHeight_ = 0L;

        change_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return liubaninc.m0.utxo.InputOuterClass.internal_static_liubaninc_m0_utxo_Output_descriptor;
      }

      @java.lang.Override
      public liubaninc.m0.utxo.InputOuterClass.Output getDefaultInstanceForType() {
        return liubaninc.m0.utxo.InputOuterClass.Output.getDefaultInstance();
      }

      @java.lang.Override
      public liubaninc.m0.utxo.InputOuterClass.Output build() {
        liubaninc.m0.utxo.InputOuterClass.Output result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public liubaninc.m0.utxo.InputOuterClass.Output buildPartial() {
        liubaninc.m0.utxo.InputOuterClass.Output result = new liubaninc.m0.utxo.InputOuterClass.Output(this);
        result.toAddr_ = toAddr_;
        if (amountBuilder_ == null) {
          result.amount_ = amount_;
        } else {
          result.amount_ = amountBuilder_.build();
        }
        result.frozenHeight_ = frozenHeight_;
        result.change_ = change_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof liubaninc.m0.utxo.InputOuterClass.Output) {
          return mergeFrom((liubaninc.m0.utxo.InputOuterClass.Output)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(liubaninc.m0.utxo.InputOuterClass.Output other) {
        if (other == liubaninc.m0.utxo.InputOuterClass.Output.getDefaultInstance()) return this;
        if (!other.getToAddr().isEmpty()) {
          toAddr_ = other.toAddr_;
          onChanged();
        }
        if (other.hasAmount()) {
          mergeAmount(other.getAmount());
        }
        if (other.getFrozenHeight() != 0L) {
          setFrozenHeight(other.getFrozenHeight());
        }
        if (other.getChange() != false) {
          setChange(other.getChange());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        liubaninc.m0.utxo.InputOuterClass.Output parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (liubaninc.m0.utxo.InputOuterClass.Output) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object toAddr_ = "";
      /**
       * <code>string to_addr = 1;</code>
       */
      public java.lang.String getToAddr() {
        java.lang.Object ref = toAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toAddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string to_addr = 1;</code>
       */
      public com.google.protobuf.ByteString
          getToAddrBytes() {
        java.lang.Object ref = toAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string to_addr = 1;</code>
       */
      public Builder setToAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string to_addr = 1;</code>
       */
      public Builder clearToAddr() {
        
        toAddr_ = getDefaultInstance().getToAddr();
        onChanged();
        return this;
      }
      /**
       * <code>string to_addr = 1;</code>
       */
      public Builder setToAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toAddr_ = value;
        onChanged();
        return this;
      }

      private cosmos.base.v1beta1.CoinOuterClass.Coin amount_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder> amountBuilder_;
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 2 [(.gogoproto.nullable) = false];</code>
       */
      public boolean hasAmount() {
        return amountBuilder_ != null || amount_ != null;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 2 [(.gogoproto.nullable) = false];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.Coin getAmount() {
        if (amountBuilder_ == null) {
          return amount_ == null ? cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : amount_;
        } else {
          return amountBuilder_.getMessage();
        }
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setAmount(cosmos.base.v1beta1.CoinOuterClass.Coin value) {
        if (amountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          amount_ = value;
          onChanged();
        } else {
          amountBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setAmount(
          cosmos.base.v1beta1.CoinOuterClass.Coin.Builder builderForValue) {
        if (amountBuilder_ == null) {
          amount_ = builderForValue.build();
          onChanged();
        } else {
          amountBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder mergeAmount(cosmos.base.v1beta1.CoinOuterClass.Coin value) {
        if (amountBuilder_ == null) {
          if (amount_ != null) {
            amount_ =
              cosmos.base.v1beta1.CoinOuterClass.Coin.newBuilder(amount_).mergeFrom(value).buildPartial();
          } else {
            amount_ = value;
          }
          onChanged();
        } else {
          amountBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearAmount() {
        if (amountBuilder_ == null) {
          amount_ = null;
          onChanged();
        } else {
          amount_ = null;
          amountBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 2 [(.gogoproto.nullable) = false];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.Coin.Builder getAmountBuilder() {
        
        onChanged();
        return getAmountFieldBuilder().getBuilder();
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 2 [(.gogoproto.nullable) = false];</code>
       */
      public cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder getAmountOrBuilder() {
        if (amountBuilder_ != null) {
          return amountBuilder_.getMessageOrBuilder();
        } else {
          return amount_ == null ?
              cosmos.base.v1beta1.CoinOuterClass.Coin.getDefaultInstance() : amount_;
        }
      }
      /**
       * <code>.cosmos.base.v1beta1.Coin amount = 2 [(.gogoproto.nullable) = false];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder> 
          getAmountFieldBuilder() {
        if (amountBuilder_ == null) {
          amountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cosmos.base.v1beta1.CoinOuterClass.Coin, cosmos.base.v1beta1.CoinOuterClass.Coin.Builder, cosmos.base.v1beta1.CoinOuterClass.CoinOrBuilder>(
                  getAmount(),
                  getParentForChildren(),
                  isClean());
          amount_ = null;
        }
        return amountBuilder_;
      }

      private long frozenHeight_ ;
      /**
       * <code>int64 frozen_height = 4;</code>
       */
      public long getFrozenHeight() {
        return frozenHeight_;
      }
      /**
       * <code>int64 frozen_height = 4;</code>
       */
      public Builder setFrozenHeight(long value) {
        
        frozenHeight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 frozen_height = 4;</code>
       */
      public Builder clearFrozenHeight() {
        
        frozenHeight_ = 0L;
        onChanged();
        return this;
      }

      private boolean change_ ;
      /**
       * <code>bool change = 5;</code>
       */
      public boolean getChange() {
        return change_;
      }
      /**
       * <code>bool change = 5;</code>
       */
      public Builder setChange(boolean value) {
        
        change_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool change = 5;</code>
       */
      public Builder clearChange() {
        
        change_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:liubaninc.m0.utxo.Output)
    }

    // @@protoc_insertion_point(class_scope:liubaninc.m0.utxo.Output)
    private static final liubaninc.m0.utxo.InputOuterClass.Output DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new liubaninc.m0.utxo.InputOuterClass.Output();
    }

    public static liubaninc.m0.utxo.InputOuterClass.Output getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Output>
        PARSER = new com.google.protobuf.AbstractParser<Output>() {
      @java.lang.Override
      public Output parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Output(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Output> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Output> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public liubaninc.m0.utxo.InputOuterClass.Output getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_liubaninc_m0_utxo_Input_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_liubaninc_m0_utxo_Input_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_liubaninc_m0_utxo_Output_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_liubaninc_m0_utxo_Output_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023m0/utxo/input.proto\022\021liubaninc.m0.utxo" +
      "\032\024gogoproto/gogo.proto\032\036cosmos/base/v1be" +
      "ta1/coin.proto\"\227\001\n\005Input\022\016\n\006ref_tx\030\001 \001(\t" +
      "\022\017\n\007ref_msg\030\002 \001(\005\022\022\n\nref_offset\030\003 \001(\005\022\021\n" +
      "\tfrom_addr\030\004 \001(\t\022/\n\006amount\030\005 \001(\0132\031.cosmo" +
      "s.base.v1beta1.CoinB\004\310\336\037\000\022\025\n\rfrozen_heig" +
      "ht\030\007 \001(\003\"q\n\006Output\022\017\n\007to_addr\030\001 \001(\t\022/\n\006a" +
      "mount\030\002 \001(\0132\031.cosmos.base.v1beta1.CoinB\004" +
      "\310\336\037\000\022\025\n\rfrozen_height\030\004 \001(\003\022\016\n\006change\030\005 " +
      "\001(\010B&Z$github.com/liubaninc/m0/x/utxo/ty" +
      "pesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          cosmos.base.v1beta1.CoinOuterClass.getDescriptor(),
        }, assigner);
    internal_static_liubaninc_m0_utxo_Input_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_liubaninc_m0_utxo_Input_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_liubaninc_m0_utxo_Input_descriptor,
        new java.lang.String[] { "RefTx", "RefMsg", "RefOffset", "FromAddr", "Amount", "FrozenHeight", });
    internal_static_liubaninc_m0_utxo_Output_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_liubaninc_m0_utxo_Output_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_liubaninc_m0_utxo_Output_descriptor,
        new java.lang.String[] { "ToAddr", "Amount", "FrozenHeight", "Change", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
    cosmos.base.v1beta1.CoinOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
